version: "3.9"

services:
  post:
    build:
      context: .
      dockerfile: 15sec_post/Dockerfile
    env_file:
      - 15sec_post/.env.container
    networks:
      - db-net
    ports:
      - '3000:3000'

networks:
  db-net:
    external: true
    name: 15sec_core_backend